name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build script
        run: ./ci/build-app.sh
      - name: Run tests
        run: ./ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
          retention-days: 1
